# Menus
menu:
  Home: .
  Archives: archives
  Categories: categories
  Tags: tags
  About: about

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: images/my-avatar.jpg
    profile:
        enabled: true # Whether to show profile bar
        avatar: css/images/my-avatar.jpg
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: Waterstrong
        author_title: Developer
        location: Chengdu, China
        follow: https://github.com/waterstrong
    highlight: monokai
    sidebar: right # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: # path to favicon
    social_links:
        github: https://github.com/waterstrong
        twitter: https://twitter.com/shuiqianglin
        facebook: https://www.facebook.com/linshuiqiang
        weixin: waterstrong
        linkedin: Shuiqiang Lin
        rss: /

# Widgets
widgets:
    - recent_posts
    - category
    - archive
    - tag
    - tagcloud
    - links

# Search
search:
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: # enter disqus shortname here
    duoshuo: waterstrong # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: bdshare # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    fancybox: true # options: true, false
    google_analytics: UA-75679138-1 # enter the tracking ID for your Google Analytics
    google_site_verification: 3uYD_HHAdzktaAWksT5naJ9iaR3GD25DNI77eRoqYlI # enter Google site verification code
    baidu_analytics: # 0eebfc18021c9d6853ca20f45d03d4a1 # enter Baidu Analytics hash key
    baidu_site_verification: # 9122feae2de1ae23df6a837a7c898ef1 # enter Baidu site verification code

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        Waterstrong Home: http://waterstrong.me
